name: Upload Docker Image of Latest Developer Branch to GHCR

on:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST
  workflow_dispatch:

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-image:
    name: Release NeuroConv Image of Current Dev Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_UPLOADER_USERNAME }}
          password: ${{ secrets.DOCKER_UPLOADER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true  # Push is a shorthand for --output=type=registry
          tags: ghcr.io/catalystneuro/neuroconv:dev
          context: dockerfiles
          file: dockerfiles/neuroconv_developer_build_dockerfile
